// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:inventory_flutter_app/utils/hive_adapter/hive_adapter.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountCategoryAdapter());
    registerAdapter(AccountStatusAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(AppConfigModelAdapter());
    registerAdapter(AppThemeAdapter());
    registerAdapter(CurrencyAdapter());
    registerAdapter(DisposalMethodAdapter());
    registerAdapter(DisposalModelAdapter());
    registerAdapter(DisposalReasonAdapter());
    registerAdapter(DisposalSortFieldAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(ItemColorsAdapter());
    registerAdapter(ItemConditionAdapter());
    registerAdapter(LanguageOptionAdapter());
    registerAdapter(NormalBalanceAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(PaymentStatusAdapter());
    registerAdapter(PurchaseItemModelAdapter());
    registerAdapter(PurchaseModelAdapter());
    registerAdapter(PurchaseStatusAdapter());
    registerAdapter(RentalModelAdapter());
    registerAdapter(RentalSortFieldAdapter());
    registerAdapter(RentalStatusAdapter());
    registerAdapter(ReportCategoryAdapter());
    registerAdapter(ReportFormatAdapter());
    registerAdapter(ReportPeriodAdapter());
    registerAdapter(ReportStatusAdapter());
    registerAdapter(SaleModelAdapter());
    registerAdapter(SalesItemModelAdapter());
    registerAdapter(SizesAdapter());
    registerAdapter(SortOrderAdapter());
    registerAdapter(StockCategoryModelAdapter());
    registerAdapter(SwapModelAdapter());
    registerAdapter(SwapReasonAdapter());
    registerAdapter(SwapSortFieldAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountCategoryAdapter());
    registerAdapter(AccountStatusAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(AppConfigModelAdapter());
    registerAdapter(AppThemeAdapter());
    registerAdapter(CurrencyAdapter());
    registerAdapter(DisposalMethodAdapter());
    registerAdapter(DisposalModelAdapter());
    registerAdapter(DisposalReasonAdapter());
    registerAdapter(DisposalSortFieldAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(ItemColorsAdapter());
    registerAdapter(ItemConditionAdapter());
    registerAdapter(LanguageOptionAdapter());
    registerAdapter(NormalBalanceAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(PaymentStatusAdapter());
    registerAdapter(PurchaseItemModelAdapter());
    registerAdapter(PurchaseModelAdapter());
    registerAdapter(PurchaseStatusAdapter());
    registerAdapter(RentalModelAdapter());
    registerAdapter(RentalSortFieldAdapter());
    registerAdapter(RentalStatusAdapter());
    registerAdapter(ReportCategoryAdapter());
    registerAdapter(ReportFormatAdapter());
    registerAdapter(ReportPeriodAdapter());
    registerAdapter(ReportStatusAdapter());
    registerAdapter(SaleModelAdapter());
    registerAdapter(SalesItemModelAdapter());
    registerAdapter(SizesAdapter());
    registerAdapter(SortOrderAdapter());
    registerAdapter(StockCategoryModelAdapter());
    registerAdapter(SwapModelAdapter());
    registerAdapter(SwapReasonAdapter());
    registerAdapter(SwapSortFieldAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
